[package]
name = "ReversibleThing"
version = "0.1.0"
edition = "2024"

[dependencies]
bit-vec = "0.8"
rand = "0.9.0"
rand_distr = "0.5.1"
itertools = "0.14.0"
rayon = "1.10.0"

[profile.release]
debug = true